/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package emd;



/**
 *
 * @author Jamil Francisco
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
     
    }
    //button function
    boolean billing1=false;
    boolean monitoring=false;
    boolean fuel=false;
    boolean workers=false;
    boolean equipment=false;
    boolean repair=false;
    boolean request=false;
    boolean search=false;
    //

    

   
  
 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        bill_btn = new javax.swing.JLabel();
        monitor_btn = new javax.swing.JLabel();
        fuel_btn = new javax.swing.JLabel();
        works_btn = new javax.swing.JLabel();
        equipment_btn = new javax.swing.JLabel();
        Repair_btn = new javax.swing.JLabel();
        search_btn = new javax.swing.JLabel();
        request_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 1220, 770));

        bill_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bill_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bill_btn.setText("BILLING");
        bill_btn.setToolTipText("");
        bill_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bill_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bill_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bill_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bill_btnMouseExited(evt);
            }
        });
        getContentPane().add(bill_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        monitor_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        monitor_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monitor_btn.setText("Monitoring");
        monitor_btn.setToolTipText("");
        monitor_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monitor_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monitor_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monitor_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monitor_btnMouseExited(evt);
            }
        });
        getContentPane().add(monitor_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 90));

        fuel_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fuel_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuel_btn.setText("Fuel");
        fuel_btn.setToolTipText("");
        fuel_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fuel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fuel_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fuel_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fuel_btnMouseExited(evt);
            }
        });
        getContentPane().add(fuel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 80));

        works_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        works_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        works_btn.setText("Workers");
        works_btn.setToolTipText("");
        works_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        works_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                works_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                works_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                works_btnMouseExited(evt);
            }
        });
        getContentPane().add(works_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 90));

        equipment_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        equipment_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipment_btn.setText("Equipment");
        equipment_btn.setToolTipText("");
        equipment_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equipment_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipment_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equipment_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equipment_btnMouseExited(evt);
            }
        });
        getContentPane().add(equipment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 100));

        Repair_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Repair_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Repair_btn.setText("Repair");
        Repair_btn.setToolTipText("");
        Repair_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Repair_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Repair_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Repair_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Repair_btnMouseExited(evt);
            }
        });
        getContentPane().add(Repair_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 100));

        search_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        search_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_btn.setText("Search");
        search_btn.setToolTipText("");
        search_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_btnMouseExited(evt);
            }
        });
        getContentPane().add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 150, 110));

        request_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        request_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        request_btn.setText("Request");
        request_btn.setToolTipText("");
        request_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        request_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                request_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                request_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                request_btnMouseExited(evt);
            }
        });
        getContentPane().add(request_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 150, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bill_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_btnMouseClicked
    billing1=true;
    monitoring=false;
    fuel=false;
    workers=false;
    equipment=false;
    repair=false;
    request=false;
    search=false;  
         BILLING bill_new = new BILLING();
          bill_new.show();
           
        
     if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add(bill_new);
           bill_new.setEnabled(true);
          bill_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                
                revalidate();
                repaint();
            }    

        
    
    }//GEN-LAST:event_bill_btnMouseClicked

    private void bill_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_btnMouseEntered

    private void bill_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_btnMouseExited

    private void monitor_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitor_btnMouseClicked
        billing1=false;
    monitoring=true;
   fuel=false;
    workers=false;
    equipment=false;
    repair=false;
     request=false;
     search=false;
        Monitoring monitor_new = new Monitoring();
          monitor_new.show();
           
        
     if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add(monitor_new);
          monitor_new.setEnabled(true);
          monitor_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                
                revalidate();
                repaint();
            }    
    }//GEN-LAST:event_monitor_btnMouseClicked

    private void monitor_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitor_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_monitor_btnMouseEntered

    private void monitor_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitor_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_monitor_btnMouseExited

    private void fuel_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fuel_btnMouseClicked
            billing1=false;
    monitoring=false;
   fuel=true;
    workers=false;
    equipment=false;
    repair=false;
     request=false;
     search=false;
         Fuel fuel_new = new Fuel();
          fuel_new.show();
           
        
     if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add( fuel_new);
          fuel_new.setEnabled(true);
           fuel_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                
                revalidate();
                repaint();
            }    
    }//GEN-LAST:event_fuel_btnMouseClicked

    private void fuel_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fuel_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_fuel_btnMouseEntered

    private void fuel_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fuel_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_fuel_btnMouseExited

    private void works_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_works_btnMouseClicked
        billing1=false;
    monitoring=false;
   fuel=false;
    workers=true;
    equipment=false;
    repair=false;
     request=false;
     search=false;
           Fuel fuel_new = new Fuel();
          fuel_new.show();
           
        
     if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add( fuel_new);
          fuel_new.setEnabled(true);
           fuel_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                
                revalidate();
                repaint();
            }    
    }//GEN-LAST:event_works_btnMouseClicked

    private void works_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_works_btnMouseEntered
     
    }//GEN-LAST:event_works_btnMouseEntered

    private void works_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_works_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_works_btnMouseExited

    private void equipment_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipment_btnMouseClicked
     billing1=false;
    monitoring=false;
   fuel=false;
    workers=false;
    equipment=true;
    repair=false;
     request=false;
     search=false;
      equipment1 equipment_new  = new equipment1();
      equipment_new.show();
     if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add(equipment_new);
          equipment_new.setEnabled(true);
          equipment_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                
                revalidate();
                repaint();
            }    
    }//GEN-LAST:event_equipment_btnMouseClicked

    private void equipment_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipment_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_equipment_btnMouseEntered

    private void equipment_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipment_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_equipment_btnMouseExited

    private void Repair_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Repair_btnMouseClicked
        billing1=false;
    monitoring=false;
   fuel=false;
    workers=false;
    equipment=true;
    repair=false;
     request=false;
     search=false;
      Repair repair_new = new Repair();
      repair_new.show();
      if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add(repair_new);
          repair_new.setEnabled(true);
          repair_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                
                revalidate();
                repaint();
            }    
      
    }//GEN-LAST:event_Repair_btnMouseClicked

    private void Repair_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Repair_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Repair_btnMouseEntered

    private void Repair_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Repair_btnMouseExited
  
    }//GEN-LAST:event_Repair_btnMouseExited

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked
    billing1=false;
    monitoring=false;
   fuel=false;
    workers=false;
    equipment=false;
    repair=false;
     request=false;
     search=true;
     
        Search search_new = new Search();
        search_new.show();
      if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add(search_new );
         search_new.setEnabled(true);
         search_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                revalidate();
                repaint();
            }    
    }//GEN-LAST:event_search_btnMouseClicked

    private void search_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_search_btnMouseEntered

    private void search_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_search_btnMouseExited

    private void request_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_request_btnMouseClicked
     billing1=false;
    monitoring=false;
   fuel=false;
    workers=false;
    equipment=false;
    repair=false;
     request=true;
     search=false;
     
        request request_new = new request();
        request_new.show();
      if (jDesktopPane1.getAllFrames().length == 0) {
         jDesktopPane1.add(request_new );
         request_new.setEnabled(true);
         request_new.isSelected();
            } else {  
                jDesktopPane1.remove(0);
                
                revalidate();
                repaint();
            }    
    }//GEN-LAST:event_request_btnMouseClicked

    private void request_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_request_btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_request_btnMouseEntered

    private void request_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_request_btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_request_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Repair_btn;
    private javax.swing.JLabel bill_btn;
    private javax.swing.JLabel equipment_btn;
    private javax.swing.JLabel fuel_btn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel monitor_btn;
    private javax.swing.JLabel request_btn;
    private javax.swing.JLabel search_btn;
    private javax.swing.JLabel works_btn;
    // End of variables declaration//GEN-END:variables
}
